Iter8
kathgod/my-shortener pull request #9
Opened 2023-01-23 14:30 UTC by kathgod

2023-01-24 15:59 UTC, mishkamashka requested changes

2023-01-24 15:59 UTC, mishkamashka commented on cmd/shortener/main.go
> +func myTest(n int) int {
Заглушки для тестов нужно выносить в отдельный файл, чтобы не мешать с основной логикой

2023-01-24 15:59 UTC, mishkamashka commented on cmd/shortener/main.go
> +	flag.Parse()
для читабельности лучше разделять логические куски отдельными строками. Вообще в го принято отделять пустой строкой объявления переменных, логические конструкци и return. Не отделяется объявление переменной, если в следующей строке оно используется или определяется
Например:
```
func a() {
    a,err := someFunc()
    if err != nil {
        log.Error(er)
    }

    b := a.Process()

    c := SomethingElse()

    var d int
    for i := 0; i < 45; i++ {
        d = a.Calculate(i)
    }

    return
}
```

2023-01-24 15:59 UTC, mishkamashka commented on internal/app/handler.go
> +const postBodyError = "Bad Post request body"
Когда констант/переменных больше одной-двух, лаконичнее объединять их в блок: 
```
const (
   postBodyError = "Bad Post request body"
   notAllowMethodError = "Not Allow method Error "
   ...
)
```

2023-01-24 15:59 UTC, mishkamashka commented on internal/app/handler.go
> +
Пустая строка сразу после объявления функции не нужна

2023-01-24 15:59 UTC, mishkamashka commented on internal/app/handler.go
> +		fileStoragePath := HandParam("FILE_STORAGE_PATH", flStoragePth)
Все инициализации из переменных лучше производить один раз на старте приложения (любые вызовы к операционной системе требуют много затрат и если какие-то параметры изменяются извне и не во время инициализации - это непредсказуемое поведение сервисов) и передавать во внутренние слои в качестве переменных внутри сртуктур, например:
```
type Api struct {
   fileStorage string
}

func NewApi(fileStorage string) *Api {
   return &Api{fileStorage}
}

func (a *Api) PostFunc(handMapPost map[string]string, handMapGet map[string]string) {
   ...   
   a.fileStorage
   ...
}
```

2023-01-24 15:59 UTC, mishkamashka commented on internal/app/handler.go
> +			log.Println(postBodyError)
Для вывода ошибок лучше использовать уровень логгирования Error, также можно использовать форматирование. Например, log.Errorf("error marshalling response: %w", err)

2023-01-24 15:59 UTC, mishkamashka commented on internal/app/handler.go
> +			rndRes := randSeq(6)
Саму логику формирования сокращенного значения лучше вынести в отдельную функцию. Обычно при реализации сервера, обрабатывающего запросы, используют архитектуру, при которой разделяют уровни хэндлеров и логики - тогда есть api  и app, api отвечает за парсинг запросов и формирование ответов, а для выполнения логики вызывает функции из app

2023-01-26 12:58 UTC, kathgod commented on internal/app/handler.go
> +			log.Println(postBodyError)
Функции Errorf в пакете log нет, по крайней мере не отобрается. соответственно поменять на конструкцию: log.Errorf("error marshalling response: %w", err), не могу

2023-01-26 17:54 UTC, kathgod commented on internal/app/handler.go
> +			rndRes := randSeq(6)
Согласна с вашим замечанием, но не могу придумать как переписать так, чтобы не переделывать половину кода

2023-01-29 14:27 UTC, mishkamashka commented on internal/app/handler.go
> +			rndRes := randSeq(6)
Иногда лучше переделать половину кода тогда, когда его еще не слишком много) В этом случае можно хотя бы только кусок, отвечающий за взаимодействие с хранилищем, выделить в отдельную функцию. Даже если это будет отдельная функция в том же файле, код уже станет намного более читабельным, так как визуально отделится та логика, которая ловит запрос, достает из него что-то, пишет ответ и та логика, которая делает какие-то манипуляции с полученными данными

Например
```
func handler(...) {
    // принимаем запрос
    // читаем body
    // проверяем корректность параметров, если надо - возвращаем 400 Bad Request
    
    // вызываем функцию, которая делает что-то внутри приложения - что-то не связанное с вводом-выводом (можно представить, что запросы-ответы - это по сути ввод-вывод)
    result, err := someSuperComplexLogic(param1, param2, ...)
    if err != nil {
        // если во внутренней системе произшла ошибка, то возвращаем 500 Internal Error, наш ввод-вывод ничего не знает о системе и может видель только результат и наличие ошибки. То, как они были получены - не его ответственность
    }
 
    // формируем ответ
    // проставляем заголовки, что-нибудь еще
    // пишем ответ
}


func someSuperComplexLogic(param1, param2, ...) SomeResult, error {
   // фунция логики, в свою очередь, ничего не знает про ввод-вывод и про то, кто и зачем ее вызывал
   // нам, как человеку, смотрящему на код, тоже становится удобно: хотим посмотреть как происходит работа с приходящими запросами - смотрим на одну функцию, хотим посмотреть на логику - смотрим другую
}

```

2023-01-29 14:28 UTC, mishkamashka commented on internal/app/handler.go
> +			log.Println(postBodyError)
Хорошо, тема логгирования еще будет в следующих спринтах, пока скорее рекомендация, если есть желание посмотреть разные пакеты логгирования

2023-01-31 16:10 UTC, mishkamashka approved these changes

2023-05-21 19:31 UTC, merged